<?php

namespace App\Http\Controllers;

use Faker\Factory;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;

    private array $categories;
    private array $news;
    private array $neededNews;

    protected function setCategories() {
        $this->categories = [
            1 => ['title' => 'Interesting category'],
            2 => ['title' => 'Not such an interesting category'],
            3 => ['title' => 'Very interesting category'],
            4 => ['title' => 'Look at this category'],
            5 => ['title' => 'I dont know what to say about this category'],
            6 => ['title' => 'OMG category'],
            7 => ['title' => 'Cars category'],
            8 => ['title' => 'Planes category'],
            9 => ['title' => 'Ships category'],
            10 => ['title' => 'Russian category'],
        ];
    }

    protected function setNews() {
        $this->news = [
            1 => ['cat' => 1, 'title' => 'art1', 'text' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam facilisis, ligula porttitor consectetur malesuada, augue augue posuere odio, id elementum tellus mauris ut magna. Vivamus vestibulum lectus eu sollicitudin auctor. Donec vehicula, sapien at vehicula dictum, enim sapien convallis est, eget interdum tellus elit vel tortor. Phasellus in semper tortor. Proin ut nunc magna. Praesent molestie risus in elit convallis ultricies. Pellentesque ac elementum sapien. Curabitur interdum metus in lorem placerat rutrum. In auctor purus vitae nunc blandit malesuada. Cras et sapien dictum risus pulvinar suscipit a eu dui. Suspendisse potenti. Pellentesque faucibus convallis congue. Aenean in vehicula turpis, quis convallis tellus. Morbi pretium turpis aliquet sem pulvinar iaculis.'],
            2 => ['cat' => 1, 'title' => 'art2', 'text' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam facilisis, ligula porttitor consectetur malesuada, augue augue posuere odio, id elementum tellus mauris ut magna. Vivamus vestibulum lectus eu sollicitudin auctor. Donec vehicula, sapien at vehicula dictum, enim sapien convallis est, eget interdum tellus elit vel tortor. Phasellus in semper tortor. Proin ut nunc magna. Praesent molestie risus in elit convallis ultricies. Pellentesque ac elementum sapien. Curabitur interdum metus in lorem placerat rutrum. In auctor purus vitae nunc blandit malesuada. Cras et sapien dictum risus pulvinar suscipit a eu dui. Suspendisse potenti. Pellentesque faucibus convallis congue. Aenean in vehicula turpis, quis convallis tellus. Morbi pretium turpis aliquet sem pulvinar iaculis.'],
            3 => ['cat' => 1, 'title' => 'art3', 'text' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam facilisis, ligula porttitor consectetur malesuada, augue augue posuere odio, id elementum tellus mauris ut magna. Vivamus vestibulum lectus eu sollicitudin auctor. Donec vehicula, sapien at vehicula dictum, enim sapien convallis est, eget interdum tellus elit vel tortor. Phasellus in semper tortor. Proin ut nunc magna. Praesent molestie risus in elit convallis ultricies. Pellentesque ac elementum sapien. Curabitur interdum metus in lorem placerat rutrum. In auctor purus vitae nunc blandit malesuada. Cras et sapien dictum risus pulvinar suscipit a eu dui. Suspendisse potenti. Pellentesque faucibus convallis congue. Aenean in vehicula turpis, quis convallis tellus. Morbi pretium turpis aliquet sem pulvinar iaculis.'],
            4 => ['cat' => 2, 'title' => 'art4', 'text' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam facilisis, ligula porttitor consectetur malesuada, augue augue posuere odio, id elementum tellus mauris ut magna. Vivamus vestibulum lectus eu sollicitudin auctor. Donec vehicula, sapien at vehicula dictum, enim sapien convallis est, eget interdum tellus elit vel tortor. Phasellus in semper tortor. Proin ut nunc magna. Praesent molestie risus in elit convallis ultricies. Pellentesque ac elementum sapien. Curabitur interdum metus in lorem placerat rutrum. In auctor purus vitae nunc blandit malesuada. Cras et sapien dictum risus pulvinar suscipit a eu dui. Suspendisse potenti. Pellentesque faucibus convallis congue. Aenean in vehicula turpis, quis convallis tellus. Morbi pretium turpis aliquet sem pulvinar iaculis.'],
            5 => ['cat' => 2, 'title' => 'art5', 'text' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam facilisis, ligula porttitor consectetur malesuada, augue augue posuere odio, id elementum tellus mauris ut magna. Vivamus vestibulum lectus eu sollicitudin auctor. Donec vehicula, sapien at vehicula dictum, enim sapien convallis est, eget interdum tellus elit vel tortor. Phasellus in semper tortor. Proin ut nunc magna. Praesent molestie risus in elit convallis ultricies. Pellentesque ac elementum sapien. Curabitur interdum metus in lorem placerat rutrum. In auctor purus vitae nunc blandit malesuada. Cras et sapien dictum risus pulvinar suscipit a eu dui. Suspendisse potenti. Pellentesque faucibus convallis congue. Aenean in vehicula turpis, quis convallis tellus. Morbi pretium turpis aliquet sem pulvinar iaculis.'],
            6 => ['cat' => 2, 'title' => 'art6', 'text' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam facilisis, ligula porttitor consectetur malesuada, augue augue posuere odio, id elementum tellus mauris ut magna. Vivamus vestibulum lectus eu sollicitudin auctor. Donec vehicula, sapien at vehicula dictum, enim sapien convallis est, eget interdum tellus elit vel tortor. Phasellus in semper tortor. Proin ut nunc magna. Praesent molestie risus in elit convallis ultricies. Pellentesque ac elementum sapien. Curabitur interdum metus in lorem placerat rutrum. In auctor purus vitae nunc blandit malesuada. Cras et sapien dictum risus pulvinar suscipit a eu dui. Suspendisse potenti. Pellentesque faucibus convallis congue. Aenean in vehicula turpis, quis convallis tellus. Morbi pretium turpis aliquet sem pulvinar iaculis.'],
            7 => ['cat' => 2, 'title' => 'art7', 'text' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam facilisis, ligula porttitor consectetur malesuada, augue augue posuere odio, id elementum tellus mauris ut magna. Vivamus vestibulum lectus eu sollicitudin auctor. Donec vehicula, sapien at vehicula dictum, enim sapien convallis est, eget interdum tellus elit vel tortor. Phasellus in semper tortor. Proin ut nunc magna. Praesent molestie risus in elit convallis ultricies. Pellentesque ac elementum sapien. Curabitur interdum metus in lorem placerat rutrum. In auctor purus vitae nunc blandit malesuada. Cras et sapien dictum risus pulvinar suscipit a eu dui. Suspendisse potenti. Pellentesque faucibus convallis congue. Aenean in vehicula turpis, quis convallis tellus. Morbi pretium turpis aliquet sem pulvinar iaculis.'],
            8 => ['cat' => 3, 'title' => 'art8', 'text' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam facilisis, ligula porttitor consectetur malesuada, augue augue posuere odio, id elementum tellus mauris ut magna. Vivamus vestibulum lectus eu sollicitudin auctor. Donec vehicula, sapien at vehicula dictum, enim sapien convallis est, eget interdum tellus elit vel tortor. Phasellus in semper tortor. Proin ut nunc magna. Praesent molestie risus in elit convallis ultricies. Pellentesque ac elementum sapien. Curabitur interdum metus in lorem placerat rutrum. In auctor purus vitae nunc blandit malesuada. Cras et sapien dictum risus pulvinar suscipit a eu dui. Suspendisse potenti. Pellentesque faucibus convallis congue. Aenean in vehicula turpis, quis convallis tellus. Morbi pretium turpis aliquet sem pulvinar iaculis.'],
            9 => ['cat' => 3, 'title' => 'art9', 'text' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam facilisis, ligula porttitor consectetur malesuada, augue augue posuere odio, id elementum tellus mauris ut magna. Vivamus vestibulum lectus eu sollicitudin auctor. Donec vehicula, sapien at vehicula dictum, enim sapien convallis est, eget interdum tellus elit vel tortor. Phasellus in semper tortor. Proin ut nunc magna. Praesent molestie risus in elit convallis ultricies. Pellentesque ac elementum sapien. Curabitur interdum metus in lorem placerat rutrum. In auctor purus vitae nunc blandit malesuada. Cras et sapien dictum risus pulvinar suscipit a eu dui. Suspendisse potenti. Pellentesque faucibus convallis congue. Aenean in vehicula turpis, quis convallis tellus. Morbi pretium turpis aliquet sem pulvinar iaculis.'],
            10 => ['cat' => 3, 'title' => 'art10', 'text' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam facilisis, ligula porttitor consectetur malesuada, augue augue posuere odio, id elementum tellus mauris ut magna. Vivamus vestibulum lectus eu sollicitudin auctor. Donec vehicula, sapien at vehicula dictum, enim sapien convallis est, eget interdum tellus elit vel tortor. Phasellus in semper tortor. Proin ut nunc magna. Praesent molestie risus in elit convallis ultricies. Pellentesque ac elementum sapien. Curabitur interdum metus in lorem placerat rutrum. In auctor purus vitae nunc blandit malesuada. Cras et sapien dictum risus pulvinar suscipit a eu dui. Suspendisse potenti. Pellentesque faucibus convallis congue. Aenean in vehicula turpis, quis convallis tellus. Morbi pretium turpis aliquet sem pulvinar iaculis.'],
            11 => ['cat' => 3, 'title' => 'art11', 'text' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam facilisis, ligula porttitor consectetur malesuada, augue augue posuere odio, id elementum tellus mauris ut magna. Vivamus vestibulum lectus eu sollicitudin auctor. Donec vehicula, sapien at vehicula dictum, enim sapien convallis est, eget interdum tellus elit vel tortor. Phasellus in semper tortor. Proin ut nunc magna. Praesent molestie risus in elit convallis ultricies. Pellentesque ac elementum sapien. Curabitur interdum metus in lorem placerat rutrum. In auctor purus vitae nunc blandit malesuada. Cras et sapien dictum risus pulvinar suscipit a eu dui. Suspendisse potenti. Pellentesque faucibus convallis congue. Aenean in vehicula turpis, quis convallis tellus. Morbi pretium turpis aliquet sem pulvinar iaculis.'],
            12 => ['cat' => 3, 'title' => 'art12', 'text' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam facilisis, ligula porttitor consectetur malesuada, augue augue posuere odio, id elementum tellus mauris ut magna. Vivamus vestibulum lectus eu sollicitudin auctor. Donec vehicula, sapien at vehicula dictum, enim sapien convallis est, eget interdum tellus elit vel tortor. Phasellus in semper tortor. Proin ut nunc magna. Praesent molestie risus in elit convallis ultricies. Pellentesque ac elementum sapien. Curabitur interdum metus in lorem placerat rutrum. In auctor purus vitae nunc blandit malesuada. Cras et sapien dictum risus pulvinar suscipit a eu dui. Suspendisse potenti. Pellentesque faucibus convallis congue. Aenean in vehicula turpis, quis convallis tellus. Morbi pretium turpis aliquet sem pulvinar iaculis.'],
            13 => ['cat' => 4, 'title' => 'art13', 'text' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam facilisis, ligula porttitor consectetur malesuada, augue augue posuere odio, id elementum tellus mauris ut magna. Vivamus vestibulum lectus eu sollicitudin auctor. Donec vehicula, sapien at vehicula dictum, enim sapien convallis est, eget interdum tellus elit vel tortor. Phasellus in semper tortor. Proin ut nunc magna. Praesent molestie risus in elit convallis ultricies. Pellentesque ac elementum sapien. Curabitur interdum metus in lorem placerat rutrum. In auctor purus vitae nunc blandit malesuada. Cras et sapien dictum risus pulvinar suscipit a eu dui. Suspendisse potenti. Pellentesque faucibus convallis congue. Aenean in vehicula turpis, quis convallis tellus. Morbi pretium turpis aliquet sem pulvinar iaculis.'],
            14 => ['cat' => 4, 'title' => 'art14', 'text' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam facilisis, ligula porttitor consectetur malesuada, augue augue posuere odio, id elementum tellus mauris ut magna. Vivamus vestibulum lectus eu sollicitudin auctor. Donec vehicula, sapien at vehicula dictum, enim sapien convallis est, eget interdum tellus elit vel tortor. Phasellus in semper tortor. Proin ut nunc magna. Praesent molestie risus in elit convallis ultricies. Pellentesque ac elementum sapien. Curabitur interdum metus in lorem placerat rutrum. In auctor purus vitae nunc blandit malesuada. Cras et sapien dictum risus pulvinar suscipit a eu dui. Suspendisse potenti. Pellentesque faucibus convallis congue. Aenean in vehicula turpis, quis convallis tellus. Morbi pretium turpis aliquet sem pulvinar iaculis.'],
            15 => ['cat' => 4, 'title' => 'art15', 'text' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam facilisis, ligula porttitor consectetur malesuada, augue augue posuere odio, id elementum tellus mauris ut magna. Vivamus vestibulum lectus eu sollicitudin auctor. Donec vehicula, sapien at vehicula dictum, enim sapien convallis est, eget interdum tellus elit vel tortor. Phasellus in semper tortor. Proin ut nunc magna. Praesent molestie risus in elit convallis ultricies. Pellentesque ac elementum sapien. Curabitur interdum metus in lorem placerat rutrum. In auctor purus vitae nunc blandit malesuada. Cras et sapien dictum risus pulvinar suscipit a eu dui. Suspendisse potenti. Pellentesque faucibus convallis congue. Aenean in vehicula turpis, quis convallis tellus. Morbi pretium turpis aliquet sem pulvinar iaculis.'],
            16 => ['cat' => 4, 'title' => 'art16', 'text' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam facilisis, ligula porttitor consectetur malesuada, augue augue posuere odio, id elementum tellus mauris ut magna. Vivamus vestibulum lectus eu sollicitudin auctor. Donec vehicula, sapien at vehicula dictum, enim sapien convallis est, eget interdum tellus elit vel tortor. Phasellus in semper tortor. Proin ut nunc magna. Praesent molestie risus in elit convallis ultricies. Pellentesque ac elementum sapien. Curabitur interdum metus in lorem placerat rutrum. In auctor purus vitae nunc blandit malesuada. Cras et sapien dictum risus pulvinar suscipit a eu dui. Suspendisse potenti. Pellentesque faucibus convallis congue. Aenean in vehicula turpis, quis convallis tellus. Morbi pretium turpis aliquet sem pulvinar iaculis.'],
            17 => ['cat' => 5, 'title' => 'art17', 'text' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam facilisis, ligula porttitor consectetur malesuada, augue augue posuere odio, id elementum tellus mauris ut magna. Vivamus vestibulum lectus eu sollicitudin auctor. Donec vehicula, sapien at vehicula dictum, enim sapien convallis est, eget interdum tellus elit vel tortor. Phasellus in semper tortor. Proin ut nunc magna. Praesent molestie risus in elit convallis ultricies. Pellentesque ac elementum sapien. Curabitur interdum metus in lorem placerat rutrum. In auctor purus vitae nunc blandit malesuada. Cras et sapien dictum risus pulvinar suscipit a eu dui. Suspendisse potenti. Pellentesque faucibus convallis congue. Aenean in vehicula turpis, quis convallis tellus. Morbi pretium turpis aliquet sem pulvinar iaculis.'],
            18 => ['cat' => 5, 'title' => 'art18', 'text' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam facilisis, ligula porttitor consectetur malesuada, augue augue posuere odio, id elementum tellus mauris ut magna. Vivamus vestibulum lectus eu sollicitudin auctor. Donec vehicula, sapien at vehicula dictum, enim sapien convallis est, eget interdum tellus elit vel tortor. Phasellus in semper tortor. Proin ut nunc magna. Praesent molestie risus in elit convallis ultricies. Pellentesque ac elementum sapien. Curabitur interdum metus in lorem placerat rutrum. In auctor purus vitae nunc blandit malesuada. Cras et sapien dictum risus pulvinar suscipit a eu dui. Suspendisse potenti. Pellentesque faucibus convallis congue. Aenean in vehicula turpis, quis convallis tellus. Morbi pretium turpis aliquet sem pulvinar iaculis.'],
            19 => ['cat' => 5, 'title' => 'art19', 'text' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam facilisis, ligula porttitor consectetur malesuada, augue augue posuere odio, id elementum tellus mauris ut magna. Vivamus vestibulum lectus eu sollicitudin auctor. Donec vehicula, sapien at vehicula dictum, enim sapien convallis est, eget interdum tellus elit vel tortor. Phasellus in semper tortor. Proin ut nunc magna. Praesent molestie risus in elit convallis ultricies. Pellentesque ac elementum sapien. Curabitur interdum metus in lorem placerat rutrum. In auctor purus vitae nunc blandit malesuada. Cras et sapien dictum risus pulvinar suscipit a eu dui. Suspendisse potenti. Pellentesque faucibus convallis congue. Aenean in vehicula turpis, quis convallis tellus. Morbi pretium turpis aliquet sem pulvinar iaculis.'],
            20 => ['cat' => 5, 'title' => 'art20', 'text' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam facilisis, ligula porttitor consectetur malesuada, augue augue posuere odio, id elementum tellus mauris ut magna. Vivamus vestibulum lectus eu sollicitudin auctor. Donec vehicula, sapien at vehicula dictum, enim sapien convallis est, eget interdum tellus elit vel tortor. Phasellus in semper tortor. Proin ut nunc magna. Praesent molestie risus in elit convallis ultricies. Pellentesque ac elementum sapien. Curabitur interdum metus in lorem placerat rutrum. In auctor purus vitae nunc blandit malesuada. Cras et sapien dictum risus pulvinar suscipit a eu dui. Suspendisse potenti. Pellentesque faucibus convallis congue. Aenean in vehicula turpis, quis convallis tellus. Morbi pretium turpis aliquet sem pulvinar iaculis.'],
            21 => ['cat' => 5, 'title' => 'art21', 'text' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam facilisis, ligula porttitor consectetur malesuada, augue augue posuere odio, id elementum tellus mauris ut magna. Vivamus vestibulum lectus eu sollicitudin auctor. Donec vehicula, sapien at vehicula dictum, enim sapien convallis est, eget interdum tellus elit vel tortor. Phasellus in semper tortor. Proin ut nunc magna. Praesent molestie risus in elit convallis ultricies. Pellentesque ac elementum sapien. Curabitur interdum metus in lorem placerat rutrum. In auctor purus vitae nunc blandit malesuada. Cras et sapien dictum risus pulvinar suscipit a eu dui. Suspendisse potenti. Pellentesque faucibus convallis congue. Aenean in vehicula turpis, quis convallis tellus. Morbi pretium turpis aliquet sem pulvinar iaculis.'],
            22 => ['cat' => 6, 'title' => 'art22', 'text' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam facilisis, ligula porttitor consectetur malesuada, augue augue posuere odio, id elementum tellus mauris ut magna. Vivamus vestibulum lectus eu sollicitudin auctor. Donec vehicula, sapien at vehicula dictum, enim sapien convallis est, eget interdum tellus elit vel tortor. Phasellus in semper tortor. Proin ut nunc magna. Praesent molestie risus in elit convallis ultricies. Pellentesque ac elementum sapien. Curabitur interdum metus in lorem placerat rutrum. In auctor purus vitae nunc blandit malesuada. Cras et sapien dictum risus pulvinar suscipit a eu dui. Suspendisse potenti. Pellentesque faucibus convallis congue. Aenean in vehicula turpis, quis convallis tellus. Morbi pretium turpis aliquet sem pulvinar iaculis.'],
            23 => ['cat' => 6, 'title' => 'art23', 'text' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam facilisis, ligula porttitor consectetur malesuada, augue augue posuere odio, id elementum tellus mauris ut magna. Vivamus vestibulum lectus eu sollicitudin auctor. Donec vehicula, sapien at vehicula dictum, enim sapien convallis est, eget interdum tellus elit vel tortor. Phasellus in semper tortor. Proin ut nunc magna. Praesent molestie risus in elit convallis ultricies. Pellentesque ac elementum sapien. Curabitur interdum metus in lorem placerat rutrum. In auctor purus vitae nunc blandit malesuada. Cras et sapien dictum risus pulvinar suscipit a eu dui. Suspendisse potenti. Pellentesque faucibus convallis congue. Aenean in vehicula turpis, quis convallis tellus. Morbi pretium turpis aliquet sem pulvinar iaculis.'],
            24 => ['cat' => 6, 'title' => 'art24', 'text' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam facilisis, ligula porttitor consectetur malesuada, augue augue posuere odio, id elementum tellus mauris ut magna. Vivamus vestibulum lectus eu sollicitudin auctor. Donec vehicula, sapien at vehicula dictum, enim sapien convallis est, eget interdum tellus elit vel tortor. Phasellus in semper tortor. Proin ut nunc magna. Praesent molestie risus in elit convallis ultricies. Pellentesque ac elementum sapien. Curabitur interdum metus in lorem placerat rutrum. In auctor purus vitae nunc blandit malesuada. Cras et sapien dictum risus pulvinar suscipit a eu dui. Suspendisse potenti. Pellentesque faucibus convallis congue. Aenean in vehicula turpis, quis convallis tellus. Morbi pretium turpis aliquet sem pulvinar iaculis.'],
            25 => ['cat' => 6, 'title' => 'art25', 'text' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam facilisis, ligula porttitor consectetur malesuada, augue augue posuere odio, id elementum tellus mauris ut magna. Vivamus vestibulum lectus eu sollicitudin auctor. Donec vehicula, sapien at vehicula dictum, enim sapien convallis est, eget interdum tellus elit vel tortor. Phasellus in semper tortor. Proin ut nunc magna. Praesent molestie risus in elit convallis ultricies. Pellentesque ac elementum sapien. Curabitur interdum metus in lorem placerat rutrum. In auctor purus vitae nunc blandit malesuada. Cras et sapien dictum risus pulvinar suscipit a eu dui. Suspendisse potenti. Pellentesque faucibus convallis congue. Aenean in vehicula turpis, quis convallis tellus. Morbi pretium turpis aliquet sem pulvinar iaculis.'],
            26 => ['cat' => 6, 'title' => 'art26', 'text' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam facilisis, ligula porttitor consectetur malesuada, augue augue posuere odio, id elementum tellus mauris ut magna. Vivamus vestibulum lectus eu sollicitudin auctor. Donec vehicula, sapien at vehicula dictum, enim sapien convallis est, eget interdum tellus elit vel tortor. Phasellus in semper tortor. Proin ut nunc magna. Praesent molestie risus in elit convallis ultricies. Pellentesque ac elementum sapien. Curabitur interdum metus in lorem placerat rutrum. In auctor purus vitae nunc blandit malesuada. Cras et sapien dictum risus pulvinar suscipit a eu dui. Suspendisse potenti. Pellentesque faucibus convallis congue. Aenean in vehicula turpis, quis convallis tellus. Morbi pretium turpis aliquet sem pulvinar iaculis.'],
            27 => ['cat' => 6, 'title' => 'art27', 'text' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam facilisis, ligula porttitor consectetur malesuada, augue augue posuere odio, id elementum tellus mauris ut magna. Vivamus vestibulum lectus eu sollicitudin auctor. Donec vehicula, sapien at vehicula dictum, enim sapien convallis est, eget interdum tellus elit vel tortor. Phasellus in semper tortor. Proin ut nunc magna. Praesent molestie risus in elit convallis ultricies. Pellentesque ac elementum sapien. Curabitur interdum metus in lorem placerat rutrum. In auctor purus vitae nunc blandit malesuada. Cras et sapien dictum risus pulvinar suscipit a eu dui. Suspendisse potenti. Pellentesque faucibus convallis congue. Aenean in vehicula turpis, quis convallis tellus. Morbi pretium turpis aliquet sem pulvinar iaculis.'],
            28 => ['cat' => 1, 'title' => 'art28', 'text' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam facilisis, ligula porttitor consectetur malesuada, augue augue posuere odio, id elementum tellus mauris ut magna. Vivamus vestibulum lectus eu sollicitudin auctor. Donec vehicula, sapien at vehicula dictum, enim sapien convallis est, eget interdum tellus elit vel tortor. Phasellus in semper tortor. Proin ut nunc magna. Praesent molestie risus in elit convallis ultricies. Pellentesque ac elementum sapien. Curabitur interdum metus in lorem placerat rutrum. In auctor purus vitae nunc blandit malesuada. Cras et sapien dictum risus pulvinar suscipit a eu dui. Suspendisse potenti. Pellentesque faucibus convallis congue. Aenean in vehicula turpis, quis convallis tellus. Morbi pretium turpis aliquet sem pulvinar iaculis.'],
            29 => ['cat' => 1, 'title' => 'art29', 'text' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam facilisis, ligula porttitor consectetur malesuada, augue augue posuere odio, id elementum tellus mauris ut magna. Vivamus vestibulum lectus eu sollicitudin auctor. Donec vehicula, sapien at vehicula dictum, enim sapien convallis est, eget interdum tellus elit vel tortor. Phasellus in semper tortor. Proin ut nunc magna. Praesent molestie risus in elit convallis ultricies. Pellentesque ac elementum sapien. Curabitur interdum metus in lorem placerat rutrum. In auctor purus vitae nunc blandit malesuada. Cras et sapien dictum risus pulvinar suscipit a eu dui. Suspendisse potenti. Pellentesque faucibus convallis congue. Aenean in vehicula turpis, quis convallis tellus. Morbi pretium turpis aliquet sem pulvinar iaculis.']

        ];
    }

    protected function getCategories(): array
    {
        $this->setCategories();
        return $this->categories;
    }

    protected function getNews($cat): array
    {
        $this->setCategories();
        $this->setNews();
        $this->neededNews = [];
        foreach ($this->news as $key => $art) {
            if ($art['cat'] == $cat){
                $this->neededNews[$key] = $art;
            }
        }
        return $this->neededNews;
    }

    protected function getSingleArticle($art_id) {
        $this->setNews();
        foreach ($this->news as $key => $article) {
            if ($key == $art_id) {
                return $article;
            }
        }
    }

    protected function getAllNews() {
        $this->setNews();
        return $this->news;
    }
}
